In [117]:
import numpy as np

data1 = [0,1,2,3,4,5,6,7,8,9]
data2 = [0.1, 5 , 4 , 0.5]

a1 = np.array(data1)
a2 = np.array(data2)

print(type(a1))
print(type(a2))

print('========================')
print(a1)
print(a2)
print('========================')
a5 = [a1]
a6 = list(a1)
print(a5)
print(a6)
a4 = a1.tolist()
print(a4)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[0.1 5.  4.  0.5]
[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [118]:
b1 = np.arange(1,11)
print(b1)
print(list(b1))
print(type(b1))
b1 = b1.tolist()
print(b1)
print(type(b1))


[ 1  2  3  4  5  6  7  8  9 10]
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


In [119]:
b1 = np.arange(1,11)
b1 = b1.reshape(2,5)
print(list(b1))
print(b1.tolist())

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [120]:
c1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
c1.tolist()


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [121]:
a1 = np.arange(0,10,2) # start,stop,step의 순서서 // stop의 숫자 미만(포함하지 않음)
a2 = np.arange(0, 10) #step이 1(1씩 증가)인 경우 생략 가능
a3 = np.arange(10) #start가 0인 경우 생략가능

print(a1)
print(a2)
print(a3)



[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [122]:
b1 = np.arange(1,51)
b1 = b1.reshape(5,10)
print(b1)
b1.shape

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


(5, 10)

In [123]:
b2 = np.linspace(0,10,50)
print(b2)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [23]:
b1.shape

(5, 10)

In [57]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [60]:
print(np.random.rand(2,3))

[[0.81304413 0.9241155  0.09178534]
 [0.02359757 0.36490862 0.65771881]]


In [64]:
print(np.random.random((2,3)))

[[0.77141117 0.68537794 0.57411503]
 [0.9559274  0.65709598 0.1447532 ]]


In [83]:
np.ones((5,3,5),int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [113]:
np.eye(5,)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [124]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
import numpy as np


print(a1)
print(a1[1])
a2 =a1[[0,2,5]]
print(a2)
print(type(a2))
print(a2.dtype)


[ 0 10 20 30 40 50]
10
[ 0 20 50]
<class 'numpy.ndarray'>
int64
[90 10 20 30 40 50]


In [25]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1[0] = 90
print(a1)

[90 10 20 30 40 50]


In [35]:
#2차원의 3 * 3 행렬 만들기
a2 = np.arange(10,100,10).reshape(3,3)
print(a2)
print()
#첫번째행 3열의 데이터 가지고오기
print(a2[0,2])

#두번째 행의 모든 데이터 가지고오기
print(a2[1])

#두번째 행의 첫번째 열의 데이터 가지고오기
print(a2[1][0])

#두번째 행의 첫번째 세번째 열의 데이터 가지고 오기
print(a2[1][[0,2]])

[[10 20 30]
 [40 50 60]
 [70 80 90]]

30
[40 50 60]
40
[40 60]


In [47]:
a3 = np.arange(10,100,10).reshape(3,3)
print(a3)
print()
#주어진 조건을 만족하면 True 아니면 False를 반환
print(a3>50)
print()
#조건에 맞는 배열을 1차원으로 반환한다.
print(a3[a3>40])
print()
#조건에 맞는 배열의 차원을 유지한 채로 반환하고싶을때
a4 = np.where(a3>40, a3, np.nan)
print(a4)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[False False False]
 [False False  True]
 [ True  True  True]]

[50 60 70 80 90]

[[nan nan nan]
 [nan 50. 60.]
 [70. 80. 90.]]


In [ ]:
np.where