In [2]:
import pandas as pd
import numpy as np

s1 = pd.Series([10,20,30,40,50,60])
s1
print(s1)
s1.shape

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64


(6,)

In [6]:
import pandas as pd

#튜플로 시리즈 만들기
data = (1,2,3,4,5,6)
print(pd.Series(data))

#리스트로 시리즈 만들기
data1 = ([1,2,3,4,5,6])
print(pd.Series(data1))

#딕셔너리로 시리즈 만들기
data1 = {1:1, 2:2, 3:3, 4:4, 5:5, 6:6}
print(pd.Series(data1)
)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64


In [7]:
import numpy as np

pd.Series(np.arange(100))

0      0
1      1
2      2
3      3
4      4
      ..
95    95
96    96
97    97
98    98
99    99
Length: 100, dtype: int32

In [26]:
s2 = pd.Series(['a','b',1.2, 5, 3.5, 'c'])
print(s2)

0      a
1      b
2    1.2
3      5
4    3.5
5      c
dtype: object


In [30]:
index_data = ['2024-08-07','2024-08-08','2024-08-09','2024-08-10','2024-08-11']
s2 = pd.Series([500, 200, np.nan, 300, np.nan ])
print(s2)
print(s2.shape)

0    500.0
1    200.0
2      NaN
3    300.0
4      NaN
dtype: float64
(5,)


In [48]:
s1 = pd.Series([10,20,30,40,50,60])

print(s1.index)
print(s1.values)
s2= s1.to_dict()
s3 = s1.to_json()
print(s2)
print(s3)

RangeIndex(start=0, stop=6, step=1)
[10 20 30 40 50 60]
{0: 10, 1: 20, 2: 30, 3: 40, 4: 50, 5: 60}
{"0":10,"1":20,"2":30,"3":40,"4":50,"5":60}


In [41]:
s5 = pd.Series({'국어':100, '영어':95, '수학':90})
print(s5)
print()
print(s5.index)
print()
print(s5.values)
print(s5.dtype)
print(type(s5))

국어    100
영어     95
수학     90
dtype: int64

Index(['국어', '영어', '수학'], dtype='object')

[100  95  90]
int64
<class 'pandas.core.series.Series'>


In [8]:
s = pd.Series([1,2,3,np.nan, 6,8])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [13]:
s=pd.Series([10,20,30],index=[1,2,3])
s1=pd.Series([10,20,30],index=['a','b','c'])

print(s)
print(s1)

1    10
2    20
3    30
dtype: int64
a    10
b    20
c    30
dtype: int64


In [17]:
s= pd.Series([9904312,3448737,289045,2466052],
index=["서울","부산","인천","대구"]) 
s.index.name = '광역시'

In [25]:
print(s)
print('========')
print(s.index)

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64
Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')


In [26]:
s.values

array([9904312, 3448737,  289045, 2466052], dtype=int64)

In [27]:
s.name='인구'
s

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64

In [16]:
print(s.index)
print(s1.index)

Index([1, 2, 3], dtype='int64')
Index(['a', 'b', 'c'], dtype='object')


In [40]:
print(f'1,3,번 인덱스 각각 추출  \n{s[[1,3]]} \n') #1,3번 인덱스 값 각각 추출
print(s[['부산','인천']]) #라벨이 부산,인천인 값 추출
print(s[0:2]) # 인덱스1
#문자 인덱스를 이용한 슬라이싱
print(s['부산':'대구'])

 1,3,번 인덱스 각각 추출  
광역시
부산    3448737
대구    2466052
Name: 인구, dtype: int64 

광역시
부산    3448737
인천     289045
Name: 인구, dtype: int64
광역시
서울    9904312
부산    3448737
Name: 인구, dtype: int64
광역시
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64


C:\Users\user\AppData\Local\Temp\ipykernel_23056\887346405.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f' 1,3,번 인덱스 각각 추출  \n{s[[1,3]]} \n') #1,3번 인덱스 값 각각 추출


In [102]:
df = pd.DataFrame
a1 = df(np.arange(1,21).reshape(4,5))

a1

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20

In [106]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [101]:
df = pd.DataFrame
a1 = df(np.arange(1,21).reshape(4,5))
a1.index= range(1,5)
a1.columns = range(1,6)

a1

1   2   3   4   5
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20

In [100]:
a3 = a1.iloc[1:, 2:]
a3.index = range(1,4)
a3.columns = range(1,4)
a3

1   2   3
1   8   9  10
2  13  14  15
3  18  19  20

In [118]:
table_data = {'연도': [2015, 2016, 2016, 2017, 2017],
              '지사': ['한국', '한국', '미국', '한국','미국'],
              '고객 수': [200, 250, 450, 300, 500]}
table_data
t1 = pd.DataFrame(table_data)
print("테이블 인덱스 : ",t1.index)
print("테이블 벨류: ",t1.values)
print("테이블 컬럼 : ",t1.columns)

테이블 인덱스 :  RangeIndex(start=0, stop=5, step=1)
테이블 벨류:  [[2015 '한국' 200]
 [2016 '한국' 250]
 [2016 '미국' 450]
 [2017 '한국' 300]
 [2017 '미국' 500]]
테이블 컬럼 :  Index(['연도', '지사', '고객 수'], dtype='object')


In [126]:
s3 = pd.Series([1, 2, 3, 4])
s4 = pd.Series([10, 20, 30, 40, 50])

print(f'뺄셈 => \n{s4 - s3}')
print(f'곱셈 => \n{s3 * s4}')


뺄셈 => 
0     9.0
1    18.0
2    27.0
3    36.0
4     NaN
dtype: float64
곱셈 => 
0     10.0
1     40.0
2     90.0
3    160.0
4      NaN
dtype: float64


In [135]:
table_data1 = {'A': [1, 2, 3, 4, 5],
              'B': [10, 20, 30, 40, 50],
              'C': [100, 200, 300, 400, 500]}
df1 = pd.DataFrame(table_data1)
print(df1)

print('====================')
table_data2 = {'A': [6, 7, 8],
              'B': [60, 70, 80],
              'C': [600, 700, 800]}
df2 = pd.DataFrame(table_data2)
print(df2)

print('==================')

print(df1+df2)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500
   A   B    C
0  6  60  600
1  7  70  700
2  8  80  800
      A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN


In [110]:
table_data3 = {'봄':  [256.5, 264.3, 215.9, 223.2, 312.8],
              '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
              '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
              '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]}
columns_list = ['봄', '여름', '가을', '겨울']
index_list = ['2012', '2013', '2014', '2015', '2016']


df3 = pd.DataFrame(table_data3, columns=columns_list, index=index_list)
df3


봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [185]:
df3.describe()

봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000

In [3]:
df1 =pd.DataFrame(np.arange(33,43).reshape(2,5))
df2 =pd.DataFrame(np.arange(20,30).reshape(5,2))

print(df1)
df1.sum(axis=1)


    0   1   2   3   4
0  33  34  35  36  37
1  38  39  40  41  42


0    175
1    200
dtype: int64

In [138]:

KTX_data = {'경부선 KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
            '호남선 KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
            '경전선 KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
            '전라선 KTX': [309, 1771, 1954, 2244, 3146, 3945, 5766],
            '동해선 KTX': [np.nan,np.nan, np.nan, np.nan, 2395, 3786, 6667]}
col_list = ['경부선 KTX','호남선 KTX','경전선 KTX','전라선 KTX','동해선 KTX']
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']
df1 = pd.DataFrame(KTX_data, columns = col_list, index = index_list)
df1

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011       39060        7313        3627         309         NaN
2012       39896        6967        4168        1771         NaN
2013       42005        6873        4088        1954         NaN
2014       43621        6626        4424        2244         NaN
2015       41702        8675        4606        3146      2395.0
2016       41266       10622        4984        3945      3786.0
2017       32427        9228        5570        5766      6667.0

In [151]:
df2 = df1.reset_index()
df2.iloc[:,1:4]

경부선 KTX  호남선 KTX  경전선 KTX
0       39060        7313        3627
1       39896        6967        4168
2       42005        6873        4088
3       43621        6626        4424
4       41702        8675        4606
5       41266       10622        4984
6       32427        9228        5570

In [126]:
type(df2)

pandas.core.frame.DataFrame

In [127]:
type(df1.loc['2011':'2014','호남선 KTX'])

pandas.core.series.Series

In [161]:
df1.index
df1.values
df1.columns

Index(['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX'], dtype='object')

In [156]:
df1.index

AttributeError: 'Index' object has no attribute 'dtypes'

In [4]:
df1 = pd.DataFrame({'class1':[95,92,98,100],
                    'class2':[91,93,97,99]})
df1

class1  class2
0      95      91
1      92      93
2      98      97
3     100      99

In [5]:
df2 = pd.DataFrame({'class1':[85,82],
                    'class2':[81,83]})
df2

class1  class2
0      85      81
1      82      83

In [6]:
catpd =pd.concat([df1,df2])
catpd

class1  class2
0      95      91
1      92      93
2      98      97
3     100      99
0      85      81
1      82      83

In [7]:
df3 = pd.DataFrame({'class1':[85,82]})
df3

class1
0      85
1      82

In [8]:
df4=pd.concat([catpd,df3]).reset_index(names='index',drop='index')
df4
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   class1  8 non-null      int64  
 1   class2  6 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 260.0 bytes


In [9]:
df1 = pd.DataFrame({'class':[93,91,95,98]})
df1

class
0     93
1     91
2     95
3     98

In [10]:
df4

class1  class2
0      95    91.0
1      92    93.0
2      98    97.0
3     100    99.0
4      85    81.0
5      82    83.0
6      85     NaN
7      82     NaN

In [193]:
jdf1=df4.join(df1)
jdf1

class1  class2  class
0      95    91.0   93.0
1      92    93.0   91.0
2      98    97.0   95.0
3     100    99.0   98.0
4      85    81.0    NaN
5      82    83.0    NaN
6      85     NaN    NaN
7      82     NaN    NaN

In [15]:
%%writefile sea_rain1.csv
연도,동해,남해,서해,전체
1996,17.4629,17.2288,14.436,15.9067
1997,17.4116,17.4092,14.8248,16.1526
1998,17.5944,18.011,15.2512,16.6044
1999,18.1495,18.3175,14.8979,16.6284
2000,17.9288,18.1766,15.0504,16.6178

Overwriting sea_rain1.csv


In [16]:
df= pd.read_csv('./sea_rain1.csv')
df

연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [17]:
%%writefile sea_rain1_space.txt
연도 동해 남해 서해 전체
1996 17.4629 17.2288 14.436 15.9067
1997 17.4116 17.4092 14.8248 16.1526
1998 17.5944 18.011 15.2512 16.6044
1999 18.1495 18.3175 14.8979 16.6284
2000 17.9288 18.1766 15.0504 16.6178

Writing sea_rain1_space.txt


In [36]:
df1 = pd.read_csv('./sea_rain1_space.txt', sep=' ')
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   연도      5 non-null      int64  
 1   동해      5 non-null      float64
 2   남해      5 non-null      float64
 3   서해      5 non-null      float64
 4   전체      5 non-null      float64
dtypes: float64(4), int64(1)
memory usage: 332.0 bytes


In [42]:
df3 = pd.read_csv('./sea_rain1.csv')
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   연도      5 non-null      int64  
 1   동해      5 non-null      float64
 2   남해      5 non-null      float64
 3   서해      5 non-null      float64
 4   전체      5 non-null      float64
dtypes: float64(4), int64(1)
memory usage: 332.0 bytes


In [86]:
df2 = pd.read_csv('./sea_rain1.csv', index_col='연도')

df2

동해       남해       서해       전체
연도                                      
1996  17.4629  17.2288  14.4360  15.9067
1997  17.4116  17.4092  14.8248  16.1526
1998  17.5944  18.0110  15.2512  16.6044
1999  18.1495  18.3175  14.8979  16.6284
2000  17.9288  18.1766  15.0504  16.6178

In [89]:
df2.drop(columns='동해')

남해       서해       전체
연도                             
1996  17.2288  14.4360  15.9067
1997  17.4092  14.8248  16.1526
1998  18.0110  15.2512  16.6044
1999  18.3175  14.8979  16.6284
2000  18.1766  15.0504  16.6178

In [39]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 1996 to 2000
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   동해      5 non-null      float64
 1   남해      5 non-null      float64
 2   서해      5 non-null      float64
 3   전체      5 non-null      float64
dtypes: float64(4)
memory usage: 200.0 bytes


In [34]:
df2.index

Index([1996, 1997, 1998, 1999, 2000], dtype='int64', name='연도')

In [43]:
df_WH = pd.DataFrame({'Weight':[62, 67, 55, 74],
                      'Height':[165, 177, 160, 180]},
index=['ID_1', 'ID_2', 'ID_3', 'ID_4'])
df_WH.index.name = 'User'
df_WH

Weight  Height
User                
ID_1      62     165
ID_2      67     177
ID_3      55     160
ID_4      74     180

In [44]:
bmi = df_WH['Weight']/(df_WH['Height']/100)**2
bmi

User
ID_1    22.773186
ID_2    21.385936
ID_3    21.484375
ID_4    22.839506
dtype: float64

In [45]:
df_WH['BMI'] = bmi
df_WH

Weight  Height        BMI
User                           
ID_1      62     165  22.773186
ID_2      67     177  21.385936
ID_3      55     160  21.484375
ID_4      74     180  22.839506

In [46]:
df_WH.to_csv('./save_BMI_dataFram.csv', encoding='cp949')

In [48]:
!type save_BMI_dataFram.csv

User,Weight,Height,BMI
ID_1,62,165,22.77318640955005
ID_2,67,177,21.38593635289987
ID_3,55,160,21.484374999999996
ID_4,74,180,22.839506172839506


In [49]:
df_pr = pd.DataFrame({'판매가격':[2000, 3000, 5000, 10000],
											'판매량':[32, 53, 40, 25]},
	index=['P1001', 'P1002', 'P1003', 'P1004'])
df_pr.index.name = '제품번호'
df_pr

판매가격  판매량
제품번호             
P1001   2000   32
P1002   3000   53
P1003   5000   40
P1004  10000   25

In [50]:
df_pr.to_csv('./save_price.txt', sep=' ', encoding='cp949')

In [51]:
!type save_price.txt

��ǰ��ȣ �ǸŰ��� �Ǹŷ�
P1001 2000 32
P1002 3000 53
P1003 5000 40
P1004 10000 25


In [53]:
s= pd.Series([9904312,3448737,289045,2466052],
index=["서울","부산","인천","대구"])
s

서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64

In [54]:
s['부산':'인천']

부산    3448737
인천     289045
dtype: int64

In [68]:
s.index.name = '광역시'
s.name='인구'
s
df = s.to_frame()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 서울 to 대구
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   인구      4 non-null      int64
dtypes: int64(1)
memory usage: 236.0+ bytes
